config/routes.rb
SermonesExpositivos::Application.routes.draw do

  devise_for :users
  root "sermons#index"
  resources :sermons

end

app/models/sermon.rb
class Sermon < ActiveRecord::Base

  default_scope order('date desc, created_at desc')

  validates_presence_of :title, :author, :date, :audio
  mount_uploader :audio, AudioUploader

  def date=(attribute)
    if attribute.class == String
      write_attribute :date, Date.strptime(attribute, "%m/%d/%Y")
    else
      write_attribute :date, attribute
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    new_sermon_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @sermons = Sermon.limit(6)
  end

end

app/controllers/sermons_controller.rb
class SermonsController < ApplicationController

  respond_to :html

  def index
    if params[:category]
      @sermons = Sermon.where(category: params[:category]).page(params[:page] || 1).per(12)
      render layout: 'home'
    else
      @black_logo = true
      @categories = Sermon.unscoped.group('category')
                          .select('category, COUNT(id) as sermons_count')
                          .where('category IS NOT NULL')
                          .order('category asc')
      render layout: 'sermons'
    end

  end

  def new
    @sermon = Sermon.new
    render layout: 'application'
  end

  def edit
    @sermon = Sermon.find params[:id]
    render layout: 'application'
  end

  def update
    @sermon = Sermon.find params[:id]
    flash[:notice] = "Sermon saved successfully" if @sermon.update_attributes(sermon_params)
    respond_with(@sermon, location: sermons_path)
  end



  def create
    @sermon = Sermon.new sermon_params
    flash[:notice] = "Sermon saved successfully" if @sermon.save
    respond_with(@sermon, location: sermons_path)
  end

  private

  def sermon_params
    params[:sermon].permit(:title, :author, :audio, :date, :category)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def header_class
    @header_class || ""
  end

  def pretty_date(date)
    date.strftime("%b %d, %Y")
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sermons_helper.rb
module SermonsHelper
end

app/views/home/index.html.haml
%h2.title
  %hr.small
  Los Mas Recientes
  %hr.large

.sermons= render @sermons

app/views/layouts/application.html.haml
!!!
%head
  %title Sermones Expositivos
  = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags

  <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,100italic,300italic,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Comfortaa:400,700,300' rel='stylesheet' type='text/css'>

%body
  - if notice
    %p.notice= notice
  - if alert
    %p.alert= alert

  .wrapper
    %header{class: header_class }
      .content
        %nav.main
          - if user_signed_in?
            = link_to 'upload a new sermon', new_sermon_path
            = link_to 'sign out', destroy_user_session_path, method: :delete
          - else
            = link_to 'sign in', new_user_session_path

        = link_to root_path do
          %h1.logo{class: @black_logo ? "black" : ""} Sermones
          %h2.logo{class: @black_logo ? "black" : ""} Expositivos


    = yield(:motto) if content_for?(:motto)
    .main.content
      .clearfix= yield
    .push

  %footer
    .content Construida Y Mantenida Por Iglesia Cristiana Gracia

app/views/layouts/home.html.haml
- content_for :motto do
  .bg
  .motto
    %h1
      Entre tanto que voy, <br /> ocúpate en la lectura, <br /> la exhortación y la enseñanza. <br />
      %span.verse 1 Timoteo 4:13
    = link_to sermons_path, class: 'button' do
      %button.white Ver Todas Nuestras Categorias

- @header_class = "nobg"
= render template: "layouts/application"

app/views/layouts/sermons.html.haml
- content_for :motto do
  .bg.sermons
  .motto.sermons

- @header_class = "nobg"
= render template: "layouts/application"

app/views/sermons/_category.html.haml
= link_to sermons_path(category: category.category) do
  .category
    = category.category
    %span.sermons-count (#{category.sermons_count})

app/views/sermons/_form.html.haml
= simple_form_for @sermon, html: {multipart: true} do |f|
  = f.input :title
  = f.input :author
  = f.input :date, as: :string
  = f.input :category
  = f.input :audio, as: :file, required: false
  = f.hidden_field :audio_cache
  = f.submit

:javascript
  $("#sermon_date").minical();

app/views/sermons/_sermon.html.haml
.sermon
  .title= sermon.title
  .sermon-content
    .download= link_to 'Bajar Audio', sermon.audio.url, data: { no_turbolink: true }
    .date= pretty_date sermon.date

  - if current_user
    .edit= link_to 'edit', edit_sermon_path(sermon)

app/views/sermons/edit.html.haml
%h2.title
  %hr.small
  Edit #{@sermon.title}
  %hr.large

= render 'form'

app/views/sermons/index.html.haml
%h2.title
  %hr.small
  - if @categories
    Los Estudios

  - if @sermons
    Los Estudios de #{params[:category]}

  %hr.large

- if @categories
  .sermons= render partial: 'category', collection: @categories, as: :category
- elsif @sermons
  .sermons= render @sermons
  = paginate @sermons

.clr

app/views/sermons/new.html.haml
%h2.title
  %hr.small
  Add a new sermon.
  %hr.large

= simple_form_for @sermon, html: {multipart: true} do |f|
  = f.input :title
  = f.input :author
  = f.input :date, as: :string
  = f.input :category
  = f.input :audio, as: :file
  = f.hidden_field :audio_cache
  = f.submit

:javascript
  $("#sermon_date").minical();